import { Account } from "@stacks/wallet-sdk";

export interface Wallet {
	/** Used when generating app private keys, which encrypt app-specific data */
	salt: string;
	/** The private key associated with the root of a BIP39 keychain */
	rootKey: string;
	/** A private key used to encrypt configuration data */
	configPrivateKey: string;
	/** The encrypted secret key */
	encryptedSecretKey: string;
	/** A list of accounts generated by this wallet */
	accounts: Account[];
}
